services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      
  kafka:
    image: confluentinc/cp-kafka:7.4.6
    ports:
      - 9093:9093
    environment:
      KAFKA_LISTENERS: SSL://:9093
      KAFKA_ADVERTISED_LISTENERS: SSL://172.29.2.137:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_SSL_KEYSTORE_FILENAME: kafka-server.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: keystore.credentials
      KAFKA_SSL_KEY_CREDENTIALS: key.credentials
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka-server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: truststore.credentials
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./secrets:/etc/kafka/secrets
    links:
      - zookeeper

  # kafkaui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-ui
  #   ports:
  #     - "8085:8080"
  #   environment:
  #     DYNAMIC_CONFIG_ENABLED: 'true'
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
  #     KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /secrets/kafkaui.keystore.jks
  #     KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: "kafkauikeystore"
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 172.29.2.137:9093
  #     KAFKA_CLUSTERS_0_SSL_TRUSTSTORELOCATION: /secrets/kafkaui.truststore.jks
  #     KAFKA_CLUSTERS_0_SSL_TRUSTSTOREPASSWORD: "dontletmedown"
  #     KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
  #   volumes:
  #     - ./clients:/secrets