version: '3.8'

services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "85:80"
    environment:
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
      MYSQL_ENV_MYSQL_USER: root
      MYSQL_ENV_MYSQL_PASSWORD: password
      MYSQL_ENV_MYSQL_DATABASE: dvwa
      UPLOAD_SIZE: 10M
      PHP_UPLOAD_MAX_FILESIZE: 10M
      PHP_POST_MAX_SIZE: 10M
    networks:
      - dvwa-net
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: dvwa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dvwa
    networks:
      - dvwa-net

networks:
  dvwa-net:

