version: '3.8'
 
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper_2
    ports:
      - "2182:2181"


  kafkasnc:
    image: wurstmeister/kafka:latest
    container_name: kafkasnc
    ports:
      - "9095:9095"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafkasnc:9093,OUTSIDE://192.168.29.185:9095 # PON TU IP DEL WIFI AQUI
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9095
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
      
  kafkaui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui_2
    ports:
      - "8086:8080"
    environment:
      
      KAFKA_CLUSTERS_0_NAME: snc
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafkasnc:9095
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2182

      DYNAMIC_CONFIG_ENABLED: 'true'