apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-ssl-deployment
  name: kafka-ssl-deployment
  namespace: kafka-ssl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ssl-deployment
  template:
    metadata:
      labels:
        app: kafka-ssl-deployment
    spec:
      dnsPolicy: Default
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumes:
        - name: kafka-ssl-volume
          persistentVolumeClaim:
            claimName: kafka-ssl-pvc
        - name: kafka-jks-secret
          secret:
            secretName: kafka-jks-secret
      containers:
        - name: kafka-ssl-deployment
          image: emstrgdevapp01.tigo.net.bo:8084/confluentinc-kafka:7.6.2
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: kafka-ssl-volume
            - name: kafka-jks-secret
              mountPath: /etc/kafka/secrets
              readOnly: true
          ports:
            - containerPort: 9093          
          env:
            - name: KAFKA_LISTENERS
              value: "SSL://:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "SSL://10.98.219.76:9093"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "10.99.193.53:2181"
            - name: KAFKA_SSL_KEYSTORE_FILENAME
              value: "kafka.server.keystore.jks"
            - name: KAFKA_SSL_KEYSTORE_CREDENTIALS
              value: "keystore.credentials"
            - name: KAFKA_SSL_KEY_CREDENTIALS
              value: "key.credentials"
            - name: KAFKA_SSL_TRUSTSTORE_FILENAME
              value: "kafka.server.truststore.jks"
            - name: KAFKA_SSL_TRUSTSTORE_CREDENTIALS
              value: "truststore.credentials"
            - name: KAFKA_SSL_CLIENT_AUTH
              value: "required"
            - name: KAFKA_SECURITY_INTER_BROKER_PROTOCOL
              value: "SSL"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LOG_DIRS
              value: /var/lib/kafka/logs-$(KAFKA_BROKER_ID)