apiVersion: v1
kind: Service
metadata:
  name: kafka-ssl-deployment
  namespace: kafka-ssl
spec:
  type: LoadBalancer
  ports:
    - port: 9093
      targetPort: 9093
  selector:
    app: kafka-ssl-deployment
